[build]
target = "./src-ui/index.html"

[watch]
ignore = ["./src-tauri"]

[serve]
address = "127.0.0.1"
port = 1420
open = false

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = [
    "-c",
    "NODE_ENV=production tailwindcss -c ./tailwind.config.js -o ./src-ui/public/css/tailwind.min.css --minify",
]
